console.log("run javascript program");
var sum = 10 + 10;
console.log(sum);
var quotient = 66 / 33;
console.log(quotient);
var myVar = 11;
myVar++;
console.log(myVar);
myVar--;
console.log(myVar);
var myName = "Zaarin";
var myString = "My name is " + myName + " and I am well.";
console.log(myString);